language: objective-c

osx_image: xcode11.2
script:
    - xcodebuild clean build test -workspace ActionSheetPicker-3.0.xcworkspace -scheme ActionSheetPicker -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro" ONLY_ACTIVE_ARCH=NO


notifications:
  email:
    recipients:
      - jki@jki.lv
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]
